### PR TITLE
Improve Readme

### PR DESCRIPTION
**Pull request by awiawi**
I just updated the README to follow [these guidelines](https://github.com/RichardLitt/standard-readme/). This makes it easier for new users to understand how to install and use this repository.

### CODE REVIEW

**Comment by awiawi** [comment]
Maybe we could improve the section about the installation a little bit further (which Matlab version is required or which toolboxes are required).

**Comment by awiawi** [comment]
Moreover, we should check why there are 2 folders (`input` and `records`) used in the script. Maybe we could combine them to one folder.

**Comment by awiawi** [comment]
> Moreover, we should check why there are 2 folders (`input` and `records`) used in the script. Maybe we could combine them to one folder.

After a first look at the code (without running it in Matlab) I think that the folder `records` is not really used. It is added in the script to the path but I think that earlier the input data was placed there and adding this folder to path makes it more convenient to add the file name (you can leave out the foldername if you enter this value).

So my suggestion would be to remove the `addpath('./records')` statement from the script and recommend to place the input data in the folder `input`.

**Review by raphajaner — APPROVED** [review]
LGTM!

**Pull request merged**
